'use strict';
const el = id => document.getElementById(id);
const fmt = stamp => stamp ? new Intl.DateTimeFormat('ja-JP', {timeZone:'Asia/Tokyo', year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(stamp)) : '未確認';
let data;
function node(tag, text, className) { const n = document.createElement(tag); if (text !== undefined) n.textContent = text; if (className) n.className = className; return n; }
function safeLink(url, text, className) { const a = node('a', text, className); try {const u = new URL(url); if(u.protocol !== 'https:') return node('span', 'リンクを確認してください'); a.href = u.href;} catch {return node('span','リンクを確認してください');} a.target='_blank'; a.rel='noopener noreferrer'; return a; }
function effectiveStatus(job) { const today = new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date()); if (job.deadline && job.deadline < today) return 'ended'; if(job.status === 'ended') return 'ended'; if(job.fetch_status !== 'ok' || !job.last_checked || Date.now()-Date.parse(job.last_checked)>3*86400000) return 'unknown'; return job.status; }
function render(){
 const q = el('q').value.normalize('NFKC').trim().toLowerCase().split(/\s+/).filter(Boolean), pref=el('pref').value, status=el('status').value;
 const jobs=data.jobs.filter(j=>{const s=effectiveStatus(j); return (!pref||j.prefecture===pref) && (status==='all'||(status==='current'?s!=='ended':s===status)) && q.every(word=>[j.hospital,j.prefecture,j.title,j.employment].join(' ').normalize('NFKC').toLowerCase().includes(word));});
 jobs.sort((a,b)=>el('sort').value==='hospital'?a.hospital.localeCompare(b.hospital,'ja'):el('sort').value==='deadline'?(a.deadline||'9999').localeCompare(b.deadline||'9999'):(b.last_checked||'').localeCompare(a.last_checked||''));
 el('count').textContent=`${jobs.length}件`; el('cards').replaceChildren();
 if(!jobs.length)el('cards').append(node('p','条件に合う情報がありません。地域や掲載状況を変更してお試しください。','empty'));
 jobs.forEach(j=>{const s=effectiveStatus(j),card=node('article',undefined,'card'),top=node('div',undefined,'card-top'); top.append(node('span',j.prefecture,'pref'),node('span',{listed:'掲載あり',unknown:'要確認',ended:'期限経過・終了'}[s]||'要確認','badge '+s)); card.append(top,node('h3',j.hospital),node('p',j.title,'job-title')); const dl=node('dl'); [['雇用形態',j.employment],['募集期限',j.deadline?j.deadline.replaceAll('-',' / '):j.deadline_note],['最終確認',fmt(j.last_checked)]].forEach(([k,v])=>{const row=node('div');row.append(node('dt',k),node('dd',v));dl.append(row);});card.append(dl);if(s==='unknown')card.append(node('p','取得失敗・情報未確認、または確認から3日以上経過しています。','warning')); const bottom=node('div',undefined,'card-bottom');bottom.append(node('small','情報源：病院公式サイト'),safeLink(j.url,'公式募集ページ ↗','official'));card.append(bottom);el('cards').append(card);});
}
async function init(){try{ const response=await fetch('jobs.json',{cache:'no-cache'});if(!response.ok)throw Error('data');data=await response.json(); if(!Array.isArray(data.jobs)||!Array.isArray(data.sources))throw Error('format');el('total').textContent=data.jobs.filter(j=>effectiveStatus(j)!=='ended').length;el('source-count').textContent=data.source_count;el('updated').textContent='最終収集：'+fmt(data.generated_at);const errors=data.sources.filter(s=>s.status!=='ok').length;if(Date.now()-Date.parse(data.generated_at)>3*86400000)el('notice').textContent='更新が3日以上確認できていません。各情報の最終確認日時と公式サイトをご確認ください。';else if(errors)el('notice').textContent=`今回、${errors}ページの取得を確認できませんでした。収集対象・取得状況から確認できます。`;[...new Set(data.jobs.map(j=>j.prefecture))].sort((a,b)=>a.localeCompare(b,'ja')).forEach(p=>{const o=node('option',p);o.value=p;el('pref').append(o);});data.sources.forEach(s=>{const row=node('div',undefined,'source-row');row.append(safeLink(s.url,s.hospital+' ↗'),node('span',s.status==='ok'?'取得確認 '+fmt(s.checked_at):'取得不可・要確認'));el('sources').append(row);});el('filters').addEventListener('submit',e=>e.preventDefault());['q','pref','status','sort'].forEach(id=>el(id).addEventListener('input',render));el('filters').addEventListener('reset',()=>setTimeout(render,0));render();}catch{el('updated').textContent='データを読み込めませんでした';el('cards').replaceChildren(node('p','採用情報を取得できません。時間をおいて再読み込みしてください。','empty'));}}
init();
